portaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard.views import login, logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('setor/', include('setor.urls')),
    path('', include('dashboard.urls')),
    path('visitante', include('visitante.urls')),
    path('acesso/', include('acesso.urls')),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout')

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setor/urls.py
from django.urls import path
from .views import list, create, update, delete

urlpatterns = [
    path('list/', list, name='setor_listar'),
    path('create/', create, name='setor_criar'),
    path('update/<int:id>/', update , name='setor_update'),
    path('delete/<int:id>/', delete , name='setor_delete'),
]

visitante/urls.py
from django.urls import path
from .views import listar, criar, atualizar, deletar, detalhar

urlpatterns = [
    path('listar/', listar, name='visitante_listar'),
    path('criar/', criar, name='visitante_criar'),
    path('atualizar/<int:id>/', atualizar , name='visitante_atualizar'),
    path('deletar/<int:id>/', deletar , name='visitante_deletar'),
    path('detalhar/<int:id>/', detalhar , name='visitante_detalhar')
]

acesso/models.py
from django.db import models

from setor.models import Setor
from visitante.models import Visitante


class Acesso(models.Model):
    data_entrada = models.DateTimeField(null=False, blank=False, verbose_name='Data de entrada')
    data_saida = models.DateTimeField(null=True, blank=True, verbose_name='Data de saída')
    setor = models.ForeignKey(Setor, null=False, blank=False, verbose_name='Setor', on_delete=models.DO_NOTHING)
    visitante = models.ForeignKey(Visitante, blank=False, null=False, verbose_name='Visitante', on_delete=models.CASCADE)
    saiu = models.BooleanField(blank=True, null=True, default=False, verbose_name='Não saiu')

    class Meta:
        verbose_name = 'Acesso'
        verbose_name_plural = 'Acessos'

pessoa/models.py
from django.db import models


SEXO_CHOICES = (
    ('M', 'Masculino'),
    ('F', 'Feminino'),
)


class Pessoa(models.Model):
    nome = models.CharField(max_length=200, null=False, blank=False, verbose_name='Nome')
    cpf = models.CharField(max_length=14, null=False, blank=False, verbose_name='CPF')
    rg = models.CharField(max_length=14, null=False, blank=False, verbose_name='RG')
    telefone = models.CharField(max_length=16, null=False, blank=False, verbose_name='Telefone')
    sexo = models.CharField(max_length=10, choices=SEXO_CHOICES, blank=True, null=True, verbose_name='Sexo')
    data_nascimento = models.DateField(null=True, blank=True, verbose_name='Data de nascimento')

    def __str__(self):
        return 'Nome: %s - CPF: %s' % (self.nome, self.cpf)

    class Meta:
        abstract = True

setor/models.py
from django.db import models

class Setor(models.Model):
    nome = models.CharField(max_length=200, null=False, blank=False, verbose_name='Nome')
    sigla = models.CharField(max_length=10, null=False, blank=False, verbose_name='Sigla')
    telefone = models.CharField(max_length=16, null=False, blank=False, verbose_name='Telefone')

    class Meta:
        verbose_name = 'Setor'
        verbose_name_plural = 'Setores'

    def __str__(self):
        return self.nome

visitante/models.py
from django.db import models
from pessoa.models import Pessoa


class Visitante(Pessoa):
    imagem = models.ImageField(upload_to='IMAGENS', null=False, blank=False, verbose_name='Imagem')

    class Meta:
        verbose_name = 'Visitante'
        verbose_name_plural = 'Visitantes'

visitante/forms.py
from django import forms
from visitante.models import Visitante


class VisitanteForm(forms.ModelForm):
    class Meta:
        model = Visitante
        fields = '__all__'

visitante/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from visitante.forms import VisitanteForm
from visitante.models import Visitante


@login_required(login_url='login')
def listar(request):

    search_item = request.GET.get('pesquisa' or None)

    if search_item:
        visitantes = Visitante.objects.filter(Q(nome__icontains=search_item) | Q(cpf__icontains=search_item) |
                                              Q(rg__icontains=search_item))
    else:
        visitantes = Visitante.objects.all().order_by('nome')
        paginator = Paginator(visitantes, 5)
        page = request.GET.get('page')
        visitantes = paginator.get_page(page)

    context = {
        'visitantes': visitantes
    }

    return render(request, 'visitante/listar.html', context)


@login_required(login_url='login')
def criar(request):
    form = VisitanteForm(request.POST or None, request.FILES or None)
    visitantes = Visitante.objects.all().order_by('-id')
    paginator = Paginator(visitantes, 5)
    page = request.GET.get('page')
    visitantes = paginator.get_page(page)

    if form.is_valid():
        form.save()
        messages.success(request, "Cadastro realizado com sucesso!")
        return redirect('visitante_listar')
    context = {
        'form': form,
        'visitantes': visitantes
    }
    return render(request, 'visitante/formulario.html', context)


@login_required(login_url='login')
def atualizar(request, id):
    visitante = get_object_or_404(Visitante, pk=id)
    form = VisitanteForm(request.POST or None, request.FILES or None, instance=visitante)
    visitantes = Visitante.objects.all()
    paginator = Paginator(visitantes, 5)
    page = request.GET.get('page')
    visitantes = paginator.get_page(page)

    if form.is_valid():
        form.save()
        messages.success(request, "Cadastro atualizado com sucesso!")
        return redirect('visitante_listar')

    context = {
        'visitantes': visitantes,
        'form': form
    }

    return render(request, 'visitante/formulario.html', context)


@login_required(login_url='login')
def deletar(request, id):
    visitante = get_object_or_404(Visitante, pk=id)
    visitantes = Visitante.objects.all()
    paginator = Paginator(visitantes, 5)
    page = request.GET.get('page')
    visitantes = paginator.get_page(page)

    if request.method == 'POST':
        visitante.delete()
        messages.success(request, "Cadastro removido com sucesso!")
        return redirect('visitante_listar')

    context = {
        'visitantes': visitantes,
        'visitante': visitante
    }
    return render(request, 'visitante/formulario_confirmar_deletar.html', context)


@login_required(login_url='login')
def detalhar(request, id):
    visitante = get_object_or_404(Visitante, pk=id)
    acessos = visitante.acesso_set.all().order_by('-id')
    paginator = Paginator(acessos, 5)
    page = request.GET.get('page')
    acessos = paginator.get_page(page)
    variaveis ={
        'visitante':visitante,
        'acessos': acessos
    }

    return render(request, 'visitante/detalhe.html', variaveis)

visitante/templates/visitante/detalhe.html
{% extends 'layout/layout.html' %}

{% block localizacao %}
<h1 class="text-light-blue">Controle de acesso</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i>Visitante</a></li>
    <li class="active">Detalhe</li>
</ol>
<br/>
<br/>
{% endblock %}

{% block conteudo %}

{% if messages %}
<div class="alert" style="background-color:#d4edda">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa icon fa fa-check"></i> Aviso!</h4>
    {% for message in messages %}
    <span {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</span>
    {% endfor %}
</div>
{% endif %}

<div class="row">
    <div class="col col-md-12" id="mensagem"></div>
</div>

<div class="row">
    <div class="col col-md-12">
        <a class="btn btn-primary" href="{% url 'acesso_criar' visitante.id %}">
            <span class="glyphicon glyphicon-plus"></span>
            Adicionar acesso
        </a>
    </div>
</div>
<br>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Tabela de acessos</h3>

                <div class="box-tools">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        {% if acessos.has_previous %}
                        <li><a href="?page=1">&laquo;&laquo;</a></li>
                        <li><a href="?page={{ acessos.previous_page_number }}">&laquo;</a></li>
                        {% endif %}

                        {% for num in acessos.paginator.page_range %}
                        {% if acessos.number == num %}
                        <li class="page-item active"><a href="?page={{ num }}">{{ num }}<span
                                class="sr-only">(current)</span></a></li>
                        {% elif num > acessos.number|add:'-3' and num < acessos.number|add:'3' %}
                        <li><a id="page_selecionado_{{num}}" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                        {% endfor %}

                        {% if acessos.has_next %}
                        <li><a href="?page={{ acessos.next_page_number }}">&raquo;</a></li>
                        <li><a href="?page={{ acessos.paginator.num_pages }}">&raquo;&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th class="hide">#</th>

                                <th class="text text-center">Data Entrada</th>

                                <th class="text text-center">Setor</th>

                                <th class="text text-center">Data de Saída</th>

                                <th class="text text-center">Situação</th>

                                <th class="text text-center">Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% include 'acesso/acesso_lista_fragmento.html' %}
                            </tbody>
                        </table>
                    </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
<h1 class="text-light-blue" style="margin-bottom:20px">Detalhe do visitante</h1>

<div class="row">
    <div class="col-md-4">
        <div class="box box-solid">
            <div class="box-header with-border text-center">
                <h3 class="box-title">Imagem</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <img src="{{ visitante.imagem.url }}" class="img-responsive img-thumbnail center-block"
                     alt=" Imagem visitante">
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <div class="col-md-8" id="dados-pessoais">
        <div class="box box-solid">
            <div class="box-header with-border text-center">
                <h3 class="box-title">Dados pessoais</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="nome">Nome</label>
                            <input type="text" value="{{visitante.nome}}" class="form-control" id="nome" disabled/>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="cpf">CPF</label>
                            <input type="text" value="{{visitante.cpf}}" class="form-control" id="cpf" disabled/>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="rg">RG</label>
                            <input type="text" value="{{visitante.rg}}" class="form-control" id="rg" disabled/>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="sexo">Sexo</label>
                            <input type="text" value="{{visitante.sexo}}" class="form-control" id="sexo" disabled/>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="telefone">Telefone</label>
                            <input type="text" value="{{visitante.telefone}}" class="form-control" id="telefone"
                                   disabled/>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
{% endblock %}

{% block jquery %}

$('.data').mask('00/00/0000');
$(".data").attr("placeholder", "00/00/0000");

$('#id_data_saida').mask('00/00/0000');
$("#id_data_saida").attr("placeholder", '00/00/0000');
{% endblock %}

visitante/templates/visitante/formulario.html
{% extends 'layout/layout.html' %}
{% load bootstrap %}

{% block localizacao %}
<h1 class="text-light-blue">Visitante</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i>Visitante</a></li>
    <li class="active">Formulário</li>
</ol>
{% endblock %}

{% block conteudo %}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Formulário</h3>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">{{ form.imagem|bootstrap }}</div>
            </div>
            <div class="row">
                <div class="col-md-8">{{ form.nome|bootstrap}}</div>
                <div class="col-md-4">{{ form.data_nascimento|bootstrap}}</div>
            </div>
            <div class="row">
                <div class="col-md-3">{{ form.cpf|bootstrap}}</div>
                <div class="col-md-3">{{ form.rg|bootstrap }}</div>
                <div class="col-md-3">{{ form.telefone|bootstrap }}</div>
                <div class="col-md-3">{{ form.sexo|bootstrap }}</div>
            </div>
        </div>
        <div class="box-footer">
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i>&nbsp&nbspSalvar</button>
            <a class="btn btn-primary" href="{% url 'visitante_listar' %}"><i class="fa fa-mail-reply-all"></i>&nbsp&nbspVoltar</a>
        </div>
    </form>
</div>
<br><br>
{% include 'visitante/visitante_lista_incompleta.html' %}
{% endblock %}

{% block jquery %}
    $('#id_cpf').mask('000.000.000-00');id_data_nascimento
    $("#id_cpf").attr("placeholder", "000.000.000-00");

    $('#id_data_nascimento').mask('00/00/0000');
    $("#id_data_nascimento").attr("placeholder", "00/00/0000");

    $('#id_telefone').mask('(00) 0-0000-0000');
    $("#id_telefone").attr("placeholder", "(00) 0-0000-0000");
{% endblock %}

visitante/templates/visitante/formulario_confirmar_deletar.html
{% extends 'layout/layout.html' %}

{% block localizacao %}
<h1>Visitante</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i>Visitante</a></li>
    <li class="active">Excluir</li>
</ol>
{% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-md-12">
        <h3 class="text-light-blue">Deletar Visitante</h3>
        <form method="POST">
            <h4>Tem certeza que deseja deletar o visitante <b>{{ visitante.nome }}</b>?</h4>
            {% csrf_token %}
            <button type="submit" class="btn btn-danger"><i class="fa fa-save"></i>&nbsp&nbspDeletar</button>
            <a class="btn btn-primary" href="{% url 'visitante_listar' %}"><i class="fa fa-mail-reply-all"></i>&nbsp&nbspVoltar</a>
        </form>
    </div>
</div>
<br>

{% include 'visitante/visitante_lista_completa.html' %}

{% endblock %}

visitante/templates/visitante/listar.html
{% extends 'layout/layout.html' %}

{% block localizacao %}
<h1 class="text-light-blue">Visitante</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i>Visitante</a></li>
    <li class="active">Lista</li>
</ol>
{% endblock %}

{% block conteudo %}
<div class="row" style="margin-bottom:10px;">
    <form action="">
        <div class="form">
            <div class="col col-md-6">
                <div class="input-group">
                    <input type="text" class="form-control" name="pesquisa"
                           placeholder="Digite Nome ou CPF ou RG">
                    <span class="input-group-btn">
                <button type="submit" class="btn btn-primary btn-flat">Buscar</button>
            </span>
                </div>
            </div>
        </div>
    </form>
</div><!-- fim row -->
<br>
<div class="row">
    <div class="col-md-12">
        <a href="{% url 'visitante_criar' %}" class="btn btn-primary">Adicionar visitante&nbsp&nbsp<i
                class="fa fa-plus"></i></a>
    </div>
</div>
<br>

{% if messages %}
<div class="alert" style="background-color:#d4edda">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa icon fa fa-check"></i> Aviso!</h4>
    {% for message in messages %}
    <span {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</span>
    {% endfor %}
</div>
{% endif %}

{% include 'visitante/visitante_lista_completa.html' %}

{% endblock %}

visitante/templates/visitante/visitante_lista_completa.html
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Tabela de Visitantes</h3>

                <div class="box-tools">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        {% if visitantes.has_previous %}
                            <li><a href="?page=1">&laquo;&laquo;</a></li>
                            <li><a href="?page={{ visitantes.previous_page_number }}">&laquo;</a></li>
                        {% endif %}

                        {% for num in visitantes.paginator.page_range %}
                            {% if visitantes.number == num %}
                                <li class="page-item active"><a href="?page={{ num }}">{{ num }}<span class="sr-only">(current)</span></a></li>
                            {% elif num > visitantes.number|add:'-3' and num < visitantes.number|add:'3' %}
                                <li><a id="page_selecionado_{{num}}" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if visitantes.has_next %}
                            <li><a  href="?page={{ visitantes.next_page_number }}">&raquo;</a></li>
                            <li><a href="?page={{ visitantes.paginator.num_pages }}">&raquo;&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tr>
                        <th class="text-center hide">ID</th>
                        <th class="text-center">Imagem</th>
                        <th class="text-center">Nome</th>
                        <th class="text-center">CPF</th>
                        <th class="text-center">RG</th>
                        <th class="text-center">Telefone</th>
                        <th class="text-center">Sexo</th>
                        <th class="text-center">Ações</th>
                    </tr>
                    {% for visitante in visitantes %}
                    <tr>
                        <td class="text-center hide">{{ visitante.id}}</td>
                        <td class="text-center">
                            <a class="tooltipped" href="{% url 'visitante_detalhar' visitante.id %}"
                               data-position="bottom"
                               data-tooltip="Ver detalhes">
                                <img style="max-height:60px;width: auto;" src="{{ visitante.imagem.url  }}"
                                     alt="foto visitante">
                            </a>
                        </td>
                        <td class="text-center">{{ visitante.nome}}</td>
                        <td class="text-center">{{ visitante.cpf}}</td>
                        <td class="text-center">{{ visitante.rg}}</td>
                        <td class="text-center">{{ visitante.telefone}}</td>
                        <td class="text-center">{{ visitante.sexo}}</td>
                        <td class="text-center">
                            <a class="" data-position="bottom" data-tooltip="Editar"
                               data-toggle="tooltip" data-placement="top" title="Editar"
                               href="{% url 'visitante_atualizar' visitante.id %}"><i class="fa  fa-pencil fa-lg"></i></a>
                            <a data-position="bottom" data-tooltip="Excluir"
                               data-toggle="tooltip" data-placement="top" title="Excluir"
                               href="{% url 'visitante_deletar' visitante.id %}"><i class="fa  fa-trash fa-lg"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>

visitante/templates/visitante/visitante_lista_incompleta.html
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Tabela de Visitantes</h3>

                <div class="box-tools hide">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        {% if visitantes.has_previous %}
                        <li><a href="?page=1">&laquo;&laquo;</a></li>
                        <li><a href="?page={{ visitantes.previous_page_number }}">&laquo;</a></li>
                        {% endif %}

                        {% for num in visitantes.paginator.page_range %}
                        {% if visitantes.number == num %}
                        <li class="page-item active"><a href="?page={{ num }}">{{ num }}<span
                                class="sr-only">(current)</span></a></li>
                        {% elif num > visitantes.number|add:'-3' and num < visitantes.number|add:'3' %}
                        <li><a id="page_selecionado_{{num}}" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                        {% endfor %}

                        {% if visitantes.has_next %}
                        <li><a href="?page={{ visitantes.next_page_number }}">&raquo;</a></li>
                        <li><a href="?page={{ visitantes.paginator.num_pages }}">&raquo;&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tr>
                        <th class="text-center hide">ID</th>
                        <th class="text-center">Imagem</th>
                        <th class="text-center">Nome</th>
                        <th class="text-center">CPF</th>
                        <th class="text-center">RG</th>
                        <th class="text-center">Telefone</th>
                        <th class="text-center">Sexo</th>
                    </tr>
                    {% for visitante in visitantes %}
                    <tr>
                        <td class="text-center hide">{{ visitante.id}}</td>
                        <td class="text-center">
                            <img style="max-height:90px;width: auto;" src="{{ visitante.imagem.url  }}"
                                 alt="foto visitante">
                        </td>
                        <td class="text-center">{{ visitante.nome}}</td>
                        <td class="text-center">{{ visitante.cpf}}</td>
                        <td class="text-center">{{ visitante.rg}}</td>
                        <td class="text-center">{{ visitante.telefone}}</td>
                        <td class="text-center">{{ visitante.sexo}}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>